// src/app/privacy/page.tsx
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Read the TCGRoll Privacy Policy.',
}

export default function PrivacyPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <p className="text-yellow-400 font-mono text-sm tracking-widest mb-2">— LEGAL</p>
      <h1 className="font-display text-6xl tracking-wide text-white mb-2">PRIVACY POLICY</h1>
      <p className="text-slate-500 font-mono text-sm mb-12">Last updated: June 2025</p>

      <div className="space-y-10 text-slate-300 leading-relaxed">

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">1. Information We Collect</h2>
          <p>We collect information you provide when creating an account (name, email address, password) and information generated by your use of the platform (card openings, token transactions, withdrawal requests including shipping address). If you sign in with Google, we receive your public profile information from that service.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">2. How We Use Your Information</h2>
          <p>Your information is used to operate your account, process token transactions, fulfill physical card withdrawals, send transactional emails (account verification, withdrawal updates), and improve the platform. We do not sell your personal data to third parties.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">3. Cookies & Analytics</h2>
          <p>We use session cookies required for authentication. We also use the following analytics and advertising services which may collect usage data:</p>
          <ul className="list-disc list-inside mt-3 space-y-1.5 text-slate-400">
            <li><strong className="text-slate-300">Google Analytics (GA4)</strong> — page views, session data, and engagement metrics</li>
            <li><strong className="text-slate-300">Google Ads</strong> — conversion tracking for advertising campaigns</li>
            <li><strong className="text-slate-300">Google Tag Manager</strong> — manages the above tracking scripts</li>
            <li><strong className="text-slate-300">Vercel Analytics</strong> — anonymous performance metrics</li>
          </ul>
          <p className="mt-3">These services operate under their own privacy policies. You can opt out of Google Analytics via <a href="https://tools.google.com/dlpage/gaoptout" className="text-yellow-400 hover:underline" target="_blank" rel="noopener noreferrer">Google's opt-out tool</a>.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">4. Data Storage & Security</h2>
          <p>Your data is stored on secure servers hosted by Vercel and Neon (PostgreSQL). Passwords are hashed using bcrypt and never stored in plain text. All data in transit is encrypted via HTTPS.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">5. Third-Party Services</h2>
          <p className="mb-3">TCGRoll uses the following third-party services to operate the platform:</p>
          <ul className="list-disc list-inside space-y-1.5 text-slate-400">
            <li><strong className="text-slate-300">Stripe</strong> — payment processing. Your card details are handled entirely by Stripe and never stored on our servers. See <a href="https://stripe.com/privacy" className="text-yellow-400 hover:underline" target="_blank" rel="noopener noreferrer">Stripe's Privacy Policy</a>.</li>
            <li><strong className="text-slate-300">Resend</strong> — transactional email delivery (account verification, withdrawal notifications). See <a href="https://resend.com/privacy" className="text-yellow-400 hover:underline" target="_blank" rel="noopener noreferrer">Resend's Privacy Policy</a>.</li>
            <li><strong className="text-slate-300">Google OAuth</strong> — optional sign-in method. See <a href="https://policies.google.com/privacy" className="text-yellow-400 hover:underline" target="_blank" rel="noopener noreferrer">Google's Privacy Policy</a>.</li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">6. Your Rights</h2>
          <p>You may request a copy of your data, correction of inaccurate data, or deletion of your account at any time by contacting us at <a href="mailto:support@tcgroll.com" className="text-yellow-400 hover:underline">support@tcgroll.com</a>. Account deletion removes all personal data within 30 days, except where retention is required by law.</p>
          <p className="mt-3"><strong className="text-slate-200">California residents (CCPA):</strong> You have the right to know what personal data we collect, request deletion, and opt out of any sale of personal information. We do not sell personal information. To exercise your rights, contact us at the address below.</p>
          <p className="mt-3"><strong className="text-slate-200">EEA/UK residents (GDPR):</strong> You have the right to access, rectify, erase, and port your personal data. You may also object to or restrict certain processing. Contact us to submit a request.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">7. Children's Privacy</h2>
          <p>TCGRoll is not intended for users under 18. We do not knowingly collect data from minors. If you believe a minor has created an account, contact us and we will delete it promptly.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">8. Contact</h2>
          <p>Privacy questions or data requests: <a href="mailto:support@tcgroll.com" className="text-yellow-400 hover:underline">support@tcgroll.com</a></p>
        </section>

      </div>
    </div>
  )
}
