// src/app/privacy/page.tsx
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Read the TCGRoll Privacy Policy.',
}

export default function PrivacyPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <p className="text-yellow-400 font-mono text-sm tracking-widest mb-2">— LEGAL</p>
      <h1 className="font-display text-6xl tracking-wide text-white mb-2">PRIVACY POLICY</h1>
      <p className="text-slate-500 font-mono text-sm mb-12">Last updated: May 2025</p>

      <div className="space-y-10 text-slate-300 leading-relaxed">

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">1. Information We Collect</h2>
          <p>We collect information you provide when creating an account (name, email, password) and information generated by your use of the platform (card openings, token transactions, withdrawal requests). If you sign in with Google or Discord, we receive your public profile information from those services.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">2. How We Use Your Information</h2>
          <p>Your information is used to operate your account, process token transactions, fulfill physical card withdrawals, send important account notifications, and improve the platform. We do not sell your personal data to third parties.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">3. Cookies & Analytics</h2>
          <p>We use session cookies required for authentication. We also use Vercel Analytics to collect anonymous usage data (page views, performance metrics) with no personally identifiable information.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">4. Data Storage & Security</h2>
          <p>Your data is stored on secure servers hosted by Vercel and Neon (PostgreSQL). Passwords are hashed using bcrypt and never stored in plain text. We use HTTPS for all data in transit.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">5. Third-Party Services</h2>
          <p>TCGRoll uses Stripe for payment processing. When you purchase tokens, your payment information is handled entirely by Stripe and never stored on our servers. Please review <a href="https://stripe.com/privacy" className="text-yellow-400 hover:underline" target="_blank" rel="noopener noreferrer">Stripe's Privacy Policy</a> for details.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">6. Your Rights</h2>
          <p>You may request a copy of your data, correction of inaccurate data, or deletion of your account at any time by contacting us. Account deletion removes all personal data within 30 days, except where retention is required by law.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">7. Children's Privacy</h2>
          <p>TCGRoll is not intended for users under 18. We do not knowingly collect data from minors. If you believe a minor has created an account, contact us and we will delete it promptly.</p>
        </section>

        <section>
          <h2 className="font-display text-2xl text-white tracking-wide mb-3">8. Contact</h2>
          <p>Privacy questions or data requests: <a href="mailto:privacy@tcgroll.com" className="text-yellow-400 hover:underline">privacy@tcgroll.com</a></p>
        </section>

      </div>
    </div>
  )
}
